package bit.app.exception;

public class ExceptionEx1 {

	public void arrayIndexOutOfBoundsException() {
		int[] m = new int[5];
		for(int i=0; i<= m.length; i++) {
			try {
				m[i] = 100;
				System.out.println("Data="+m[i]);
			} catch (ArrayIndexOutOfBoundsException e) {
				System.out.println(e.getMessage());
			} finally {
				System.out.println("finally");
			}
		}
	}
	
	public static void main(String[] args) {
		ExceptionEx1 e = new ExceptionEx1();
		e.arrayIndexOutOfBoundsException();
	}
}
